name: "💬 Other"
description: "Something else"
title: "[Other] "
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      placeholder: "Tell us what's on your mind"
    validations:
      required: false
